POST http://localhost:3000/campaigns 
content-type: application/json

{
    "name": "jeferson 2",
    "content": "change password",
    "emails": ["jefersonactf@gmail.com"]
}

### 
GET http://localhost:3000/campaigns 